# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15623fe8908c541b89d01218395bc2709633d0f010686a692d5f2224ff24bb293c7176219c0a5118df9862fee42cfd9e32af16073cc51732f7c23a580dfc4293

test:
  secret_key_base: 733a04a035bed61a4b7303f9fa519c8fd3806f3d06cad135186ccc2a039b20298c4a8c17119b88071dc23e0203e6c5c7cfe8bde7996bb81ade8b917070b428e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
